# /repositories/base.py
from abc import ABC, abstractmethod
from typing import List

class BaseRepository(ABC):

    @abstractmethod
    def get_user_by_id(self, user_id: str): ...

    @abstractmethod
    def get_album(self, album_id: int): ...
    @abstractmethod
    def get_track(self, track_id: int): ...
    @abstractmethod
    def get_artist(self, artist_id: int): ...
    @abstractmethod
    def get_playlist(self, playlist_id: int): ...

    @abstractmethod
    def all_albums(self): ...
    @abstractmethod
    def all_artists(self): ...
    @abstractmethod
    def all_tracks(self): ...
    @abstractmethod
    def all_playlists(self): ...

    @abstractmethod
    def create_playlist(self, user_id: str, name: str) -> int: ...
    @abstractmethod
    def update_playlist_tracks(self, playlist_id: int, track_ids: List[int], action: str): ...

    @abstractmethod
    def update_user_like(self, user_id: str, obj_type: str, obj_id: int, like: bool): ...
    @abstractmethod
    def get_user_by_username(self, username: str): ...
    @abstractmethod
    def delete_playlist(self, user_id: str, playlist_id: int): ...